"""POSCAR / INCAR / KPOINTS writers."""

from __future__ import annotations

from typing import Dict, List, Optional, Sequence

from . import potentials
from .cell_model import Cell, kpoint_mesh_from_density, sorted_by_species

TASKS = (
    "Single point (SCF)",
    "Relax ions",
    "Relax ions + cell",
    "Density of states",
    "Band structure (non-SCF)",
    "Molecular dynamics (NVT)",
)

FUNCTIONALS = ("PBE (POTCAR default)", "PBEsol", "RPBE", "PS (PBEsol)", "LDA (CA)")

VDW_OPTIONS = ("None", "DFT-D2 (IVDW=1)", "DFT-D3 (IVDW=11)", "DFT-D3(BJ) (IVDW=12)", "TS (IVDW=2)")

SMEARING = (
    "Gaussian (ISMEAR=0)",
    "Methfessel-Paxton 1 (ISMEAR=1)",
    "Fermi (ISMEAR=-1)",
    "Tetrahedron + Blochl (ISMEAR=-5)",
)

KPOINT_MODES = ("Gamma-only", "Gamma-centred mesh", "Monkhorst-Pack mesh", "Automatic (spacing)")

COORD_MODES = ("Direct (fractional)", "Cartesian")


def default_settings() -> Dict:
    return {
        "title": "Generated by MoleditPy VASP Input Generator",
        "task": TASKS[0],
        "functional": FUNCTIONALS[0],
        "encut": 520.0,
        "ediff": 1e-6,
        "ediffg": -0.02,
        "nsw": 100,
        "prec": "Accurate",
        "algo": "Normal",
        "nelm": 120,
        "lreal": "Auto",
        "ncore": 4,
        "ispin": False,
        "magmom_auto": True,
        "smearing": SMEARING[0],
        "sigma": 0.05,
        "vdw": VDW_OPTIONS[0],
        "lwave": False,
        "lcharg": True,
        "isym": 2,
        "extra_incar": "",
        "kpoint_mode": KPOINT_MODES[1],
        "kmesh": [4, 4, 4],
        "kshift": [0.0, 0.0, 0.0],
        "kspacing": 0.03,
        "coord_mode": COORD_MODES[0],
        "selective_dynamics": False,
        "frozen_indices": [],
        "recommended_potcar": True,
        "temperature": 300.0,
        "potim": 1.0,
        "supercell": [1, 1, 1],
        "padding": 6.0,
        "cubic_box": False,
    }


# --------------------------------------------------------------------------
# POSCAR
# --------------------------------------------------------------------------


def build_poscar(cell: Cell, settings: Optional[Dict] = None) -> str:
    settings = {**default_settings(), **(settings or {})}
    atoms, counts = sorted_by_species(cell)

    lines: List[str] = []
    title = str(settings.get("title") or cell.name).strip() or "POSCAR"
    lines.append(title.replace("\n", " "))
    lines.append("   1.00000000000000")
    for vector in cell.lattice:
        lines.append(
            "  {: >21.16f} {: >21.16f} {: >21.16f}".format(*[float(v) for v in vector])
        )
    lines.append("  " + "  ".join(f"{element:>4}" for element, _ in counts))
    lines.append("  " + "  ".join(f"{count:>4d}" for _, count in counts))

    selective = bool(settings.get("selective_dynamics"))
    frozen = set(int(index) for index in settings.get("frozen_indices") or [])
    if selective:
        lines.append("Selective dynamics")

    cartesian = settings.get("coord_mode") == COORD_MODES[1]
    lines.append("Cartesian" if cartesian else "Direct")

    # frozen_indices refer to the *original* cell ordering, so map through the
    # species sort rather than using the emitted row number.
    order = []
    for _, indices in _species_indices(cell):
        order.extend(indices)

    for row, atom in enumerate(atoms):
        values = atom.cart if cartesian else atom.fract
        line = "  {: >19.16f} {: >19.16f} {: >19.16f}".format(*[float(v) for v in values])
        if selective:
            flag = "F   F   F" if order[row] in frozen else "T   T   T"
            line += f"   {flag}"
        line += f"   ! {atom.label}"
        lines.append(line)

    return "\n".join(lines) + "\n"


def _species_indices(cell: Cell):
    from .cell_model import group_by_species

    return group_by_species(cell)


# --------------------------------------------------------------------------
# INCAR
# --------------------------------------------------------------------------


def _task_tags(settings: Dict) -> List[tuple]:
    task = settings.get("task", TASKS[0])
    nsw = int(settings.get("nsw", 100))
    tags: List[tuple] = []

    if task == "Single point (SCF)":
        tags += [("IBRION", -1), ("NSW", 0)]
    elif task == "Relax ions":
        tags += [("IBRION", 2), ("ISIF", 2), ("NSW", nsw), ("EDIFFG", settings.get("ediffg", -0.02))]
    elif task == "Relax ions + cell":
        tags += [("IBRION", 2), ("ISIF", 3), ("NSW", nsw), ("EDIFFG", settings.get("ediffg", -0.02))]
    elif task == "Density of states":
        tags += [("IBRION", -1), ("NSW", 0), ("LORBIT", 11), ("NEDOS", 3001)]
    elif task == "Band structure (non-SCF)":
        tags += [("IBRION", -1), ("NSW", 0), ("ICHARG", 11), ("LORBIT", 11)]
    elif task == "Molecular dynamics (NVT)":
        tags += [
            ("IBRION", 0),
            ("MDALGO", 2),
            ("SMASS", 0),
            ("NSW", max(1, nsw)),
            ("POTIM", settings.get("potim", 1.0)),
            ("TEBEG", settings.get("temperature", 300.0)),
            ("TEEND", settings.get("temperature", 300.0)),
        ]
    return tags


def _functional_tags(settings: Dict) -> List[tuple]:
    functional = settings.get("functional", FUNCTIONALS[0])
    if functional.startswith("PBE ("):
        return []  # PBE POTCARs already carry GGA = PE
    if functional.startswith("PBEsol") or functional.startswith("PS"):
        return [("GGA", "PS")]
    if functional.startswith("RPBE"):
        return [("GGA", "RP")]
    if functional.startswith("LDA"):
        return [("GGA", "CA")]
    return []


def _vdw_tags(settings: Dict) -> List[tuple]:
    mapping = {
        "DFT-D2 (IVDW=1)": 1,
        "TS (IVDW=2)": 2,
        "DFT-D3 (IVDW=11)": 11,
        "DFT-D3(BJ) (IVDW=12)": 12,
    }
    value = mapping.get(settings.get("vdw", "None"))
    return [("IVDW", value)] if value else []


def _smearing_tags(settings: Dict) -> List[tuple]:
    task = settings.get("task")
    label = settings.get("smearing", SMEARING[0])
    ismear = {
        "Gaussian (ISMEAR=0)": 0,
        "Methfessel-Paxton 1 (ISMEAR=1)": 1,
        "Fermi (ISMEAR=-1)": -1,
        "Tetrahedron + Blochl (ISMEAR=-5)": -5,
    }.get(label, 0)
    if task == "Density of states" and ismear >= 0:
        ismear = -5  # tetrahedron gives a far smoother DOS
    tags = [("ISMEAR", ismear)]
    if ismear >= -1:
        tags.append(("SIGMA", settings.get("sigma", 0.05)))
    return tags


def build_incar(settings: Optional[Dict] = None, counts: Optional[Sequence] = None) -> str:
    settings = {**default_settings(), **(settings or {})}

    tags: List[tuple] = [
        ("SYSTEM", str(settings.get("title") or "MoleditPy").replace("\n", " ")),
        ("PREC", settings.get("prec", "Accurate")),
        ("ENCUT", settings.get("encut", 520.0)),
        ("EDIFF", settings.get("ediff", 1e-6)),
        ("ALGO", settings.get("algo", "Normal")),
        ("NELM", int(settings.get("nelm", 120))),
        ("LREAL", settings.get("lreal", "Auto")),
        ("ISYM", int(settings.get("isym", 2))),
    ]
    tags += _functional_tags(settings)
    tags += _smearing_tags(settings)
    tags += _task_tags(settings)

    if settings.get("ispin"):
        tags.append(("ISPIN", 2))
        if settings.get("magmom_auto") and counts:
            tags.append(("MAGMOM", potentials.magmom_defaults(counts)))

    tags += _vdw_tags(settings)
    tags.append(("LWAVE", ".TRUE." if settings.get("lwave") else ".FALSE."))
    tags.append(("LCHARG", ".TRUE." if settings.get("lcharg") else ".FALSE."))
    ncore = int(settings.get("ncore", 0) or 0)
    if ncore > 1:
        tags.append(("NCORE", ncore))

    lines = [f"{key:<8}= {_format_value(value)}" for key, value in tags]

    extra = str(settings.get("extra_incar") or "").strip()
    if extra:
        lines.append("")
        lines.append("! --- additional tags ---")
        lines.extend(extra.splitlines())

    return "\n".join(lines) + "\n"


def _format_value(value) -> str:
    if isinstance(value, bool):
        return ".TRUE." if value else ".FALSE."
    if isinstance(value, float):
        if value != 0 and (abs(value) < 1e-3 or abs(value) >= 1e5):
            return f"{value:.1E}"
        return f"{value:g}"
    return str(value)


# --------------------------------------------------------------------------
# KPOINTS
# --------------------------------------------------------------------------


def build_kpoints(cell: Cell, settings: Optional[Dict] = None) -> str:
    settings = {**default_settings(), **(settings or {})}
    mode = settings.get("kpoint_mode", KPOINT_MODES[1])

    if mode == "Gamma-only":
        mesh, shift, centring = (1, 1, 1), (0.0, 0.0, 0.0), "Gamma"
    elif mode == "Automatic (spacing)":
        mesh = kpoint_mesh_from_density(cell, float(settings.get("kspacing", 0.03)))
        shift, centring = (0.0, 0.0, 0.0), "Gamma"
    else:
        mesh = tuple(max(1, int(value)) for value in settings.get("kmesh", [4, 4, 4]))
        shift = tuple(float(value) for value in settings.get("kshift", [0.0, 0.0, 0.0]))
        centring = "Monkhorst-Pack" if mode.startswith("Monkhorst") else "Gamma"

    header = f"Automatic mesh ({mode})"
    return (
        f"{header}\n0\n{centring}\n"
        f"  {mesh[0]:d}  {mesh[1]:d}  {mesh[2]:d}\n"
        f"  {shift[0]:g}  {shift[1]:g}  {shift[2]:g}\n"
    )


# --------------------------------------------------------------------------
# POTCAR helper + bundle
# --------------------------------------------------------------------------


def build_potcar_notes(cell: Cell, settings: Optional[Dict] = None) -> str:
    settings = {**default_settings(), **(settings or {})}
    _, counts = sorted_by_species(cell)
    elements = [element for element, _ in counts]
    recommended = bool(settings.get("recommended_potcar", True))
    names = potentials.potcar_names(elements, recommended)

    lines = [
        "# POTCAR is licensed VASP data and cannot be generated here.",
        "# Concatenate the files in the SAME element order as POSCAR:",
        "#",
        f"#   {'  '.join(elements)}",
        "#",
        potentials.concat_command(names),
    ]
    missing = potentials.unmapped_elements(elements)
    if missing and recommended:
        lines.append(
            "# No recommended-set entry for: "
            + ", ".join(missing)
            + " (plain symbol used)."
        )
    return "\n".join(lines) + "\n"


def build_all(cell: Cell, settings: Optional[Dict] = None) -> Dict[str, str]:
    settings = {**default_settings(), **(settings or {})}
    _, counts = sorted_by_species(cell)
    return {
        "POSCAR": build_poscar(cell, settings),
        "INCAR": build_incar(settings, counts),
        "KPOINTS": build_kpoints(cell, settings),
        "POTCAR.readme": build_potcar_notes(cell, settings),
    }


def build_preview(cell: Cell, settings: Optional[Dict] = None) -> str:
    files = build_all(cell, settings)
    chunks = []
    for name in ("INCAR", "KPOINTS", "POSCAR", "POTCAR.readme"):
        chunks.append(f"{'=' * 28} {name} {'=' * 28}\n{files[name]}")
    return "\n".join(chunks)
